name: Publish

on:
  push:
    branches:
      - 'master'

  workflow_run:
    workflows: ['Test']
    types:
      - completed

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout Repository
        uses: actions/checkout@v2

      - run: |
          yarn install --frozen-lockfile
          yarn build-prod

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true

      - run: |
          echo ${{ secrets.NPM_REGISTRY }} >> .npmrc
          npx google-artifactregistry-auth .npmrc
